"""Add soft delete fields to CapaIssue

Revision ID: e71563afe6b2
Revises: 
Create Date: 2025-05-27 11:44:04.881793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e71563afe6b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_knowledge_base', schema=None) as batch_op:
        # batch_op.alter_column('capa_id',
        #        existing_type=mysql.INTEGER(display_width=11),
        #        nullable=False)
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        # batch_op.create_foreign_key(None, 'capa_issues', ['capa_id'], ['capa_id'])
        batch_op.drop_column('migration_temp_flag_v1')

    with op.batch_alter_table('capa_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.drop_column('category_id')
        batch_op.drop_column('initial_photo_path')
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capa_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('initial_photo_path', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('ai_knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migration_temp_flag_v1', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('capa_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
